- name: Install Nginx
  hosts: all
  tasks:
  - name: Install ngnix
    apt:
      update_cache: yes
      name: nginx
      state: latest
  - name: Start nginx
    systemd:
      name: nginx
      enabled: true
      state: started
  